### ISSUE TITLE
Missing Code?

### ISSUE THREAD

**Issue by kingsgate-pre** [planningcenter/projector#2]
Hello PCO!

I'm starting to see what it would cost to update this app and have had the following response from a development team after they tried to build the code that is currently on GitHub.

"Some user interfaces are there but we need the missing package to run it.

For e.g. pod Projector.xcworkspace file and some other frameworks are missing.

We then created a new project and added following pods

pod 'MCTColorPicker', '~> 0.1'
pod 'Shimmer', '~> 1.0'

Due to dependencies we imported files into a new project.

After completing some exercise <MCTDataCache/MCTDataCache.h> and other framework were found missing.

We understand we need to use the new Api 2.0 from planning center but the codebase in it’s current state can’t be used"

Does that sound about right? Are you able to supply the missing code to help us move this forward? 
Thanks for all you do!
Matt

**Comment by bensie** [comment]
@kingsgate MCTDataCache is open source and available at https://github.com/ministrycentered/MCTDataCache

You'd need to rebuild the workspace file from a fresh cocoapods install.

Given that the entire data and API layer is not included, there are a lot of reasons you won't be able to get the code to build as-is. It will take a considerable amount of work to add an API and data layer that is powered by APIv2. We've supplied everything we can to provide a starting point. Good luck!
